/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.doctor.view.util;

import com.jidesoft.swing.AutoCompletion;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import lk.ijse.doctor.controller.ControllerFactory;
import lk.ijse.doctor.controller.custom.AppoinmentController;
import lk.ijse.doctor.controller.custom.DoctorController;
import lk.ijse.doctor.controller.custom.PatientController;
import lk.ijse.doctor.controller.custom.RegistrationController;
import lk.ijse.doctor.dto.PatientDTO;
import lk.ijse.doctor.dto.RegistrationDTO;
import lk.ijse.doctor.idgenerator.IdGenerator;

/**
 *
 * @author sameera
 */
public class AddPatients extends javax.swing.JPanel {
    
    private AppoinmentController ctrlAppointment;
    private PatientController ctrlPatient;
    private RegistrationController ctrlRegistration;
    private DoctorController ctrlDoctor;
    private String gender;
    private String doctorname="";

    /**
     * Creates new form MakeAppointment
     */
    public AddPatients() {
        initComponents();
        ctrlRegistration=(RegistrationController) ControllerFactory.getInstance().getController(ControllerFactory.ControllerTypes.REGISTRATION);
        ctrlPatient=(PatientController) ControllerFactory.getInstance().getController(ControllerFactory.ControllerTypes.PATIENT);
        ctrlDoctor =(DoctorController) ControllerFactory.getInstance().getController(ControllerFactory.ControllerTypes.DOCTOR);
        ctrlAppointment =(AppoinmentController) ControllerFactory.getInstance().getController(ControllerFactory.ControllerTypes.APPOINMENT);
        loadIds();
        setEnablePatient(false);
        clearFiledPatient();

        
        AutoCompletion ac =new AutoCompletion(cmbLoadRegistrationIds);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void setEnablePatient(boolean enable, JComponent... cmp) {
        txtPatientId.setEnabled(enable);
        txtPatientName.setEnabled(enable);
        txtPatientAddress.setEnabled(enable);
        cmbGender.setEnabled(enable);
        txtNic.setEnabled(enable);
        txtAge.setEnabled(enable);
        txtTelephoneNo.setEnabled(enable);
        btnSave.setEnabled(enable);
        for (JComponent jcmp : cmp) {
            jcmp.setEnabled(!enable);
        }
    }
    private void clearFiledPatient(){
        txtPatientId.setText("");
        txtPatientName.setText("");
        txtPatientAddress.setText("");
        cmbGender.setSelectedItem("");
        txtNic.setText("");
        txtAge.setText("");
        txtTelephoneNo.setText("");
   }
   private void doValidataPatient(){
       String ptid =txtPatientId.getText();
       String name=txtPatientName.getText();
       String address=txtPatientAddress.getText();
       String gender=(String) cmbGender.getSelectedItem();
       String nic =txtNic.getText();
       String age =txtAge.getText();
       String teleno =txtTelephoneNo.getText();
       
       btnSave.setEnabled(false);
       
       if(!ptid.isEmpty()){
           if(name.matches("[A-Za-z ]+")){
               if(!address.isEmpty()){
                   if(!gender.isEmpty()){
                       if(nic.matches("\\d{9}[V]")){
                           if(!age.isEmpty()){
                               if(teleno.matches("\\d{10}")){
                                   btnSave.setEnabled(true);
                               }
                           }
                       }
                   }
               }
           }
       }
   } 
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBack = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cmbLoadRegistrationIds = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        txtPatientId = new javax.swing.JTextField();
        txtPatientName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtPatientAddress = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtNic = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtTelephoneNo = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnNewPatient = new javax.swing.JButton();
        cmbGender = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(1140, 657));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlBack.setMinimumSize(new java.awt.Dimension(1141, 657));
        pnlBack.setPreferredSize(new java.awt.Dimension(1141, 657));
        pnlBack.setLayout(new javax.swing.BoxLayout(pnlBack, javax.swing.BoxLayout.LINE_AXIS));

        jPanel2.setMinimumSize(new java.awt.Dimension(1141, 657));
        jPanel2.setPreferredSize(new java.awt.Dimension(1140, 657));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Registration Id :");

        cmbLoadRegistrationIds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbLoadRegistrationIdsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addComponent(cmbLoadRegistrationIds, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbLoadRegistrationIds, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Patient Id :");

        txtPatientId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPatientIdKeyReleased(evt);
            }
        });

        txtPatientName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPatientNameKeyReleased(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Patient Name :");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Patient Address :");

        txtPatientAddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPatientAddressKeyReleased(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Gender :");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("NIC :");

        txtNic.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNicKeyReleased(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("Age :");

        txtAge.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAgeKeyReleased(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setText("Telephone No :");

        txtTelephoneNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTelephoneNoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTelephoneNoKeyReleased(evt);
            }
        });

        btnSave.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnNewPatient.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnNewPatient.setText("New Patient");
        btnNewPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewPatientActionPerformed(evt);
            }
        });

        cmbGender.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "FeMale" }));
        cmbGender.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cmbGenderKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(102, 102, 102)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTelephoneNo)
                                    .addComponent(txtAge)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(102, 102, 102)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(cmbGender, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(txtNic)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(102, 102, 102)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPatientAddress)
                                    .addComponent(txtPatientName)
                                    .addComponent(txtPatientId)))
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(btnNewPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21))))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(btnNewPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtPatientId, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtPatientName)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtPatientAddress)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(cmbGender, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNic)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtAge)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTelephoneNo)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("Add Patient");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(521, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        pnlBack.add(jPanel2);

        add(pnlBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1140, 660));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        SelectDoctor selectDoctor=new SelectDoctor();
        pnlBack.removeAll();
        pnlBack.repaint();
        pnlBack.revalidate();
        pnlBack.add(selectDoctor);
        selectDoctor.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cmbLoadRegistrationIdsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbLoadRegistrationIdsActionPerformed
        
        
        String rgid=(String) cmbLoadRegistrationIds.getSelectedItem();
        
        try {
            RegistrationDTO registration =ctrlRegistration.search(rgid);
            txtPatientName.setText(registration.getName());
            txtPatientAddress.setText(registration.getAddress());
            cmbGender.setSelectedItem(registration.getGender());
            txtNic.setText(registration.getNic());
            txtAge.setText(""+registration.getAge());
            txtTelephoneNo.setText(""+registration.getTeleno());
           
           
        } catch (Exception ex) {
            Logger.getLogger(AddPatients.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_cmbLoadRegistrationIdsActionPerformed

    private void btnNewPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewPatientActionPerformed
        clearFiledPatient();
        
        setEnablePatient(true,btnSave);
        txtPatientName.requestFocusInWindow();
        
         try {
            String id =IdGenerator.getNewRegistrationIds("Patient", "ptid", "P");
            txtPatientId.setText(id);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(RegistrationPatient.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(RegistrationPatient.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnNewPatientActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        String ptid = txtPatientId.getText();
        String name = txtPatientName.getText();
        String address = txtPatientAddress.getText();
        if (cmbGender.getSelectedItem().equals("Male")) {
            gender = "Male";
        }
        if (cmbGender.getSelectedItem().equals("FeMale")) {
            gender = "FeMale";
        }
        String nic = txtNic.getText();
        int age = Integer.parseInt(txtAge.getText());
        int teleno = Integer.parseInt(txtTelephoneNo.getText());
        
        PatientDTO patient =new PatientDTO(ptid, name, address, gender, nic, age, teleno);
        
        try {
            boolean added =false;
            if(txtPatientId.isEnabled()){
                added =ctrlPatient.add(patient);
            }
            if(added){
                clearFiledPatient();
                setEnablePatient(false);
                btnNewPatient.requestFocusInWindow();
            }else{
                ImageIcon icons = new ImageIcon(this.getClass().getResource("/lk/ijse/doctor/icons/error_icon.png"));
                JOptionPane.showMessageDialog(this,
                        "Patient has been fail to add",
                        "Error",
                        JOptionPane.ERROR_MESSAGE,
                        icons);
                txtPatientId.requestFocusInWindow();
                txtPatientId.selectAll();
            }
        }catch(SQLException ex){
            String errormsg;
            
            ImageIcon icons = new ImageIcon(this.getClass().getResource("/lk/ijse/doctor/icons/error_icon.png"));
            
            switch(ex.getErrorCode()){
                case 1062:
                    errormsg="Duplicate entry has been found. Please enter valid Patient Id to proceed.";
                    break;
                    default:
                        errormsg="Patient has been fail to add";
                       break;
                        
            }
            
            JOptionPane.showMessageDialog(this,
                    errormsg,
                    "Error",
                    JOptionPane.ERROR_MESSAGE,
                    icons);
            txtPatientId.requestFocusInWindow();
            txtPatientId.selectAll();
        } catch (Exception ex) {
            Logger.getLogger(AddPatients.class.getName()).log(Level.SEVERE, null, ex);
        }
        MakaAppointmentForm makaAppointment =new MakaAppointmentForm();
        pnlBack.removeAll();
        pnlBack.repaint();
        pnlBack.revalidate();
        pnlBack.add(makaAppointment);
        makaAppointment.setVisible(true);
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtPatientIdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPatientIdKeyReleased
        doValidataPatient();
    }//GEN-LAST:event_txtPatientIdKeyReleased

    private void txtPatientNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPatientNameKeyReleased
        doValidataPatient();
    }//GEN-LAST:event_txtPatientNameKeyReleased

    private void txtPatientAddressKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPatientAddressKeyReleased
        doValidataPatient();
    }//GEN-LAST:event_txtPatientAddressKeyReleased

    private void cmbGenderKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmbGenderKeyReleased
        doValidataPatient();
    }//GEN-LAST:event_cmbGenderKeyReleased

    private void txtNicKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNicKeyReleased
        doValidataPatient();
    }//GEN-LAST:event_txtNicKeyReleased

    private void txtAgeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAgeKeyReleased
        doValidataPatient();
    }//GEN-LAST:event_txtAgeKeyReleased

    private void txtTelephoneNoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelephoneNoKeyReleased
        doValidataPatient();
    }//GEN-LAST:event_txtTelephoneNoKeyReleased

    private void txtTelephoneNoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelephoneNoKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            btnSave.doClick();
        }
    }//GEN-LAST:event_txtTelephoneNoKeyPressed

    private void loadIds(){
        
        try {
            
            ArrayList<String>rgidList=ctrlRegistration.getAllRegIds();
            for(String id : rgidList){
                cmbLoadRegistrationIds.addItem(id);
            }
        } catch (Exception ex) {
            Logger.getLogger(AddPatients.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNewPatient;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox cmbGender;
    private javax.swing.JComboBox cmbLoadRegistrationIds;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel pnlBack;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtNic;
    private javax.swing.JTextField txtPatientAddress;
    private javax.swing.JTextField txtPatientId;
    private javax.swing.JTextField txtPatientName;
    private javax.swing.JTextField txtTelephoneNo;
    // End of variables declaration//GEN-END:variables

}
